<a href="https://colab.research.google.com/github/Anusarakh/thesis/blob/main/12_oct_23_FV_ML_DEMO_Version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1️⃣ เชื่อม google drive

In [1]:
#เชื่อม google drive
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
#เข้าไป path ใน google drive
import os
os.chdir('/content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิพนธ์/เพลง/')

!pwd #เช็ค paht ที่กำลังทำงานอยู่

/content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิพนธ์/เพลง


# 2️⃣ Data preparation by FV

In [3]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
import csv
import scipy.io.wavfile as wav

In [4]:
classes_1 = 1
classes_0 = 0

path_1 = '/content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิพนธ์/เพลง/เพลงที่โรคซึมเศร้าไม่ควรฟัง/'
path_0 = '/content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิพนธ์/เพลง/เพลงสำหรับโรคซึมเศร้า/'

In [5]:
x_list = os.listdir(path_0)
mfcc_mean_0 = []
#mfcc_var_0 = []
spec_cen_mean_0 = []
#spec_cen_var_0 = []
spec_band_mean_0 = []
#spec_band_var_0 = []
zcr_mean_0 = []
#zcr_var_0 = []
tempo = []
classes_0_ = []
tempo_0 = []
for i in x_list:
  x , sr = librosa.load(path_0+i, sr=44100)
  #สกัด MFCC
  mfcc = librosa.feature.mfcc(y=x, sr=44100 ,n_mfcc= 20, n_fft = 512,  hop_length=256 )
  df_mfcc = pd.DataFrame(mfcc)
  mfcc_mean = df_mfcc.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล MFCC
  #mfcc_var= df_mfcc.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล MFCC
  #สกัด spectral_centroid
  spec_cen = librosa.feature.spectral_centroid(y=x, sr=44100, S=None, n_fft=512, hop_length=256)
  df_spec_cen = pd.DataFrame(spec_cen)
  spec_cen_mean = df_spec_cen.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล spectral_centroid
  #spec_cen_var= df_spec_cen.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล spectral_centroid
  #สกัด spectral_bandwidth
  spec_band = librosa.feature.spectral_bandwidth(y=x, sr=44100, S=None, n_fft=512, hop_length=256)
  df_spec_band = pd.DataFrame(spec_band)
  spec_band_mean = df_spec_band.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล spectral_bandwidth
  #spec_band_var= df_spec_band.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล spectral_bandwidth
  #สกัด zero_crossing_rate
  zcr = librosa.feature.zero_crossing_rate(y=x, frame_length=512, hop_length=256)
  df_zcr = pd.DataFrame(zcr)
  zcr_mean = df_zcr.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล zero_crossing_rate
  #zcr_var= df_zcr.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล zero_crossing_rate
  #สกัด tempo
  tempo = librosa.feature.tempo(y=x, sr=44100 , hop_length=256)

  mfcc_mean_0.append(list(mfcc_mean))
  #mfcc_var_0.append(list(mfcc_var))
  spec_cen_mean_0.append(spec_cen_mean[0])
  #spec_cen_var_0.append(spec_cen_var[0])
  spec_band_mean_0.append(spec_band_mean[0])
  #spec_band_var_0.append(spec_band_var[0])
  zcr_mean_0.append(zcr_mean[0])
  #zcr_var_0.append(zcr_var[0])
  tempo_0.append(tempo[0])

  classes_0_.append(path_0+i)

/usr/local/lib/python3.10/dist-packages/librosa/feature/spectral.py:2143: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = filters.mel(sr=sr, n_fft=n_fft, **kwargs)
<ipython-input-5-e221b5f8bbdf>:14: UserWarning: PySoundFile failed. Trying audioread instead.
  x , sr = librosa.load(path_0+i, sr=44100)
/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py:183: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/usr/local/lib/python3.10/dist-packages/librosa/feature/spectral.py:2143: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = filters.mel(sr=sr, n_fft=n_fft, **kwa

In [6]:
x_list = os.listdir(path_1)
mfcc_mean_1 = []
#mfcc_var_1 = []
spec_cen_mean_1 = []
#spec_cen_var_1 = []
spec_band_mean_1 = []
#spec_band_var_1 = []
zcr_mean_1 = []
#zcr_var_1 = []
tempo = []
classes_1_ = []
tempo_1 = []
for i in x_list:
  x , sr = librosa.load(path_1+i, sr=44100)
  #สกัด MFCC
  mfcc = librosa.feature.mfcc(y=x, sr=44100 ,n_mfcc= 20, n_fft = 512,  hop_length=256 )
  df_mfcc = pd.DataFrame(mfcc)
  mfcc_mean = df_mfcc.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล MFCC
  #mfcc_var= df_mfcc.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล MFCC
  #สกัด spectral_centroid
  spec_cen = librosa.feature.spectral_centroid(y=x, sr=44100, S=None, n_fft=512, hop_length=256)
  df_spec_cen = pd.DataFrame(spec_cen)
  spec_cen_mean = df_spec_cen.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล spectral_centroid
  #spec_cen_var= df_spec_cen.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล spectral_centroid
  #สกัด spectral_bandwidth
  spec_band = librosa.feature.spectral_bandwidth(y=x, sr=44100, S=None, n_fft=512, hop_length=256)
  df_spec_band = pd.DataFrame(spec_band)
  spec_band_mean = df_spec_band.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล spectral_bandwidth
  #spec_band_var= df_spec_band.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล spectral_bandwidth
  #สกัด zero_crossing_rate
  zcr = librosa.feature.zero_crossing_rate(y=x, frame_length=512, hop_length=256)
  df_zcr = pd.DataFrame(zcr)
  zcr_mean = df_zcr.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล zero_crossing_rate
  #zcr_var= df_zcr.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล zero_crossing_rate
  #สกัด tempo
  tempo = librosa.feature.tempo(y=x, sr=44100, hop_length=256)


  mfcc_mean_1.append(list(mfcc_mean))
  #mfcc_var_1.append(list(mfcc_var))
  spec_cen_mean_1.append(spec_cen_mean[0])
  #spec_cen_var_1.append(spec_cen_var[0])
  spec_band_mean_1.append(spec_band_mean[0])
  #spec_band_var_1.append(spec_band_var[0])
  zcr_mean_1.append(zcr_mean[0])
  #zcr_var_1.append(zcr_var[0])
  tempo_1.append(tempo[0])

  classes_1_.append(path_1+i)

In [7]:
mfcc_mean_0 = np.array(mfcc_mean_0)
mfcc_mean_1 = np.array(mfcc_mean_1)

mfcc_mean_df = pd.DataFrame(data = mfcc_mean_0)
mfcc_mean_df['spec'] = spec_cen_mean_0
mfcc_mean_df['specband'] = spec_band_mean_0
mfcc_mean_df['zero'] = zcr_mean_0
mfcc_mean_df['tempo'] = tempo_0
mfcc_mean_df['y'] = 0
mfcc_mean_df['path'] = classes_0_

mfcc_mean_df_1 = pd.DataFrame(data = mfcc_mean_1)
mfcc_mean_df_1['spec'] = spec_cen_mean_1
mfcc_mean_df_1['specband'] = spec_band_mean_1
mfcc_mean_df_1['zero'] = zcr_mean_1
mfcc_mean_df_1['tempo'] = tempo_1
mfcc_mean_df_1['y'] = 1
mfcc_mean_df_1['path'] = classes_1_

df_mean = mfcc_mean_df.append(mfcc_mean_df_1)

print(df_mean.shape)
df_mean.head()

(55, 26)


<ipython-input-7-8ce7a2c1c5a2>:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_mean = mfcc_mean_df.append(mfcc_mean_df_1)


0           1          2          3         4          5  \
0 -538.598083  113.478355 -26.311657  14.285193 -2.615120  20.236992   
1 -534.914490  130.501404  20.693159  -0.368550  3.864216  10.282823   
2 -341.382050   87.907219 -68.019501  21.463785 -9.300843  29.104156   
3 -341.382050   87.907219 -68.019501  21.463785 -9.300843  29.104156   
4 -333.593781   89.235611 -48.172359  33.847538  0.143549  21.800449   

          6          7          8          9  ...        16        17  \
0 -7.610242   1.884620 -11.387437 -11.193010  ... -2.539678 -4.401006   
1 -7.931257  -3.838516  -6.757467  -8.169674  ... -4.494755 -2.965578   
2 -9.891349  10.565740 -14.902565  -4.446410  ...  0.327383 -2.359935   
3 -9.891349  10.565740 -14.902565  -4.446410  ...  0.327383 -2.359935   
4 -5.154069   3.627782  -8.566092  -2.217165  ... -2.934254 -2.611754   

         18        19         spec     specband      zero       tempo  y  \
0 -0.343688  1.216539  1543.771776  2381.031060  0.028983  147.656250  0   
1 -1.883306 -2.093495   978.482703  1580.413853  0.022765  100.348908  0   
2  3.743439 -2.977661  2332.112785  2752.448472  0.057955  147.656250  0   
3  3.743439 -2.977661  2332.112785  2752.448472  0.057955  147.656250  0   
4  1.254204 -3.089329  2168.881015  2760.755593  0.048477  121.599265  0   

                                                path  
0  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  
1  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  
2  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  
3  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  
4  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  

[5 rows x 26 columns]

In [8]:
#mfcc_var_0 = np.array(mfcc_var_0)
#mfcc_var_1 = np.array(mfcc_var_1)

#mfcc_var_df = pd.DataFrame(data = mfcc_var_0)
#mfcc_var_df['spec'] = spec_cen_var_0
#mfcc_var_df['specband'] = spec_band_var_0
#mfcc_var_df['zero'] = zcr_var_0
#mfcc_var_df['tempo'] = tempo_0
#mfcc_var_df['y'] = 0
#mfcc_var_df['path'] = classes_0_

#mfcc_var_df_1 = pd.DataFrame(data = mfcc_var_1)
#mfcc_var_df_1['spec'] = spec_cen_var_1
#mfcc_var_df_1['specband'] = spec_band_var_1
#mfcc_var_df_1['zero'] = zcr_var_1
#mfcc_var_df_1['tempo'] = tempo_1
#mfcc_var_df_1['y'] = 1
#mfcc_var_df_1['path'] = classes_1_

#df_var = mfcc_var_df.append(mfcc_var_df_1)

#print(df_var.shape)
#df_var.head()

## Split data train/teast by 80:20

In [9]:
df_mean.head()

0           1          2          3         4          5  \
0 -538.598083  113.478355 -26.311657  14.285193 -2.615120  20.236992   
1 -534.914490  130.501404  20.693159  -0.368550  3.864216  10.282823   
2 -341.382050   87.907219 -68.019501  21.463785 -9.300843  29.104156   
3 -341.382050   87.907219 -68.019501  21.463785 -9.300843  29.104156   
4 -333.593781   89.235611 -48.172359  33.847538  0.143549  21.800449   

          6          7          8          9  ...        16        17  \
0 -7.610242   1.884620 -11.387437 -11.193010  ... -2.539678 -4.401006   
1 -7.931257  -3.838516  -6.757467  -8.169674  ... -4.494755 -2.965578   
2 -9.891349  10.565740 -14.902565  -4.446410  ...  0.327383 -2.359935   
3 -9.891349  10.565740 -14.902565  -4.446410  ...  0.327383 -2.359935   
4 -5.154069   3.627782  -8.566092  -2.217165  ... -2.934254 -2.611754   

         18        19         spec     specband      zero       tempo  y  \
0 -0.343688  1.216539  1543.771776  2381.031060  0.028983  147.656250  0   
1 -1.883306 -2.093495   978.482703  1580.413853  0.022765  100.348908  0   
2  3.743439 -2.977661  2332.112785  2752.448472  0.057955  147.656250  0   
3  3.743439 -2.977661  2332.112785  2752.448472  0.057955  147.656250  0   
4  1.254204 -3.089329  2168.881015  2760.755593  0.048477  121.599265  0   

                                                path  
0  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  
1  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  
2  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  
3  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  
4  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  

[5 rows x 26 columns]

In [10]:
path = df_mean[df_mean['y']== 0]['path'].tolist()
# print(len(path))
from random import sample
res_samle_0 = sample(path,int(len(path)*0.8))
print(len(set(res_samle_0)))

path = df_mean[df_mean['y']== 1]['path'].tolist()
# print(len(path))
from random import sample
res_samle_1 = sample(path,int(len(path)*0.8))
print(len(set(res_samle_1)))

res_samle_0.extend(res_samle_1)

print(len(res_samle_0))

13
30
43


In [11]:
train = df_mean[df_mean['path'].isin(res_samle_0)]
train['split'] = 'train'
test = df_mean[~df_mean['path'].isin(res_samle_0)]
test['split'] = 'test'

df_all = train.append(test)
print(df_all.shape)
df_all.head()

(55, 27)


<ipython-input-11-d13c214b5ed7>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['split'] = 'train'
<ipython-input-11-d13c214b5ed7>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['split'] = 'test'
<ipython-input-11-d13c214b5ed7>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = train.append(test)


0           1          2          3          4          5  \
1 -534.914490  130.501404  20.693159  -0.368550   3.864216  10.282823   
3 -341.382050   87.907219 -68.019501  21.463785  -9.300843  29.104156   
4 -333.593781   89.235611 -48.172359  33.847538   0.143549  21.800449   
6 -269.983276   81.923279 -62.945431  40.809315 -12.077918  28.884892   
7 -544.917664  137.602142  -9.134362  12.341524   3.336396   4.093431   

           6          7          8         9  ...        17        18  \
1  -7.931257  -3.838516  -6.757467 -8.169674  ... -2.965578 -1.883306   
3  -9.891349  10.565740 -14.902565 -4.446410  ... -2.359935  3.743439   
4  -5.154069   3.627782  -8.566092 -2.217165  ... -2.611754  1.254204   
6 -11.093246  10.458975 -12.508752 -3.473673  ... -6.861853  2.739935   
7   9.600341 -16.092543 -11.178644 -5.225426  ... -3.947825  0.528342   

         19         spec     specband      zero       tempo  y  \
1 -2.093495   978.482703  1580.413853  0.022765  100.348908  0   
3 -2.977661  2332.112785  2752.448472  0.057955  147.656250  0   
4 -3.089329  2168.881015  2760.755593  0.048477  121.599265  0   
6 -1.447447  2657.452458  3136.322421  0.061271  104.403409  0   
7 -2.570315   886.860665  1201.144385  0.023065  130.834652  0   

                                                path  split  
1  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  train  
3  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  train  
4  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  train  
6  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  train  
7  /content/gdrive/MyDrive/Thesis/เค้าโครงวิทยานิ...  train  

[5 rows x 27 columns]

In [12]:
# var fv same table
#df_var['split'] = df_var['path'].map(df_all.set_index('path')['split']) # can map column split by path column
#df_var.head()

# 3️⃣ ML// Random Forest Classifier

In [13]:
# X_train

In [14]:
import os
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

## Mean fv

In [15]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

n_estimators = [400]
max_depth = [5, 8, 15, 25, 30]
min_samples_split = [2, 5, 10, 15, 100]
forest = RandomForestClassifier(random_state = 1)
hyperF ={'n_estimators' : n_estimators, 'max_depth' : max_depth, 'min_samples_split' : min_samples_split}
gridF = GridSearchCV(forest, hyperF, cv = 3, verbose = 1, n_jobs = -1)
bestF = gridF.fit(X_train, y_train)
bestF_ = bestF.best_params_

forestOpt = RandomForestClassifier(random_state = 1, max_depth = bestF_['max_depth'], n_estimators = bestF_['n_estimators'], min_samples_split =bestF_['min_samples_split'])
modelOpt = forestOpt.fit(X_train, y_train)

print(bestF_)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
{'max_depth': 5, 'min_samples_split': 5, 'n_estimators': 400}


In [16]:
y_pred = modelOpt.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.75      0.75         4
           1       0.88      0.88      0.88         8

    accuracy                           0.83        12
   macro avg       0.81      0.81      0.81        12
weighted avg       0.83      0.83      0.83        12

[[3 1]
 [1 7]]


## Mean fv- Normalization

In [17]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

X_train_norm = np.linalg.norm(X_train)
X_train_norm = X_train/X_train_norm

X_test_norm = np.linalg.norm(X_test)
X_test_norm = X_test/X_test_norm


n_estimators = [400]
max_depth = [5, 8, 15, 25, 30]
min_samples_split = [2, 5, 10, 15, 100]
forest = RandomForestClassifier(random_state = 1)
hyperF ={'n_estimators' : n_estimators, 'max_depth' : max_depth, 'min_samples_split' : min_samples_split}
gridF = GridSearchCV(forest, hyperF, cv = 3, verbose = 1, n_jobs = -1)
bestF = gridF.fit(X_train_norm, y_train)
bestF_ = bestF.best_params_

forestOpt = RandomForestClassifier(random_state = 1, max_depth = bestF_['max_depth'], n_estimators = bestF_['n_estimators'], min_samples_split =bestF_['min_samples_split'])
modelOpt = forestOpt.fit(X_train_norm, y_train)

print(bestF_)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
{'max_depth': 5, 'min_samples_split': 5, 'n_estimators': 400}


In [18]:
y_pred = modelOpt.predict(X_test_norm)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         4
           1       0.80      1.00      0.89         8

    accuracy                           0.83        12
   macro avg       0.90      0.75      0.78        12
weighted avg       0.87      0.83      0.81        12

[[2 2]
 [0 8]]


# 4️⃣ ML // SVM Classifier

## Mean fv

In [19]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

In [20]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

Cs = [0.001, 0.01, 0.1, 1, 10]
gammas = [0.001, 0.01, 0.1, 1]
kernels = ['linear', 'rbf', 'poly']

svm= svm.SVC()
param_grid = {'C': Cs, 'gamma' : gammas, 'kernel' : kernels}
grid_search = GridSearchCV(svm, param_grid, cv=5)

SVM = grid_search.fit(X_train, y_train)

# examine the first result
print("**examine the first result","\n")

print(SVM.cv_results_['params'][0])
print(SVM.cv_results_['mean_test_score'][0])

# print the array of mean scores only
print("\n","**print the array of mean scores only","\n")

grid_mean_scores = SVM.cv_results_['mean_test_score']
print(grid_mean_scores)

# examine the best model
print("\n","**examine the best model","\n")
bestS_ = SVM.best_params_
print(SVM.best_score_)
print(SVM.best_params_)
print(SVM.best_estimator_)

**examine the first result 

{'C': 0.001, 'gamma': 0.001, 'kernel': 'linear'}
0.7027777777777777

 **print the array of mean scores only 

[0.70277778 0.7        0.65277778 0.70277778 0.7        0.65277778
 0.70277778 0.7        0.65277778 0.70277778 0.7        0.65277778
 0.71944444 0.7        0.65277778 0.71944444 0.7        0.65277778
 0.71944444 0.7        0.65277778 0.71944444 0.7        0.65277778
 0.67222222 0.7        0.65277778 0.67222222 0.7        0.65277778
 0.67222222 0.7        0.65277778 0.67222222 0.7        0.65277778
 0.67222222 0.7        0.65277778 0.67222222 0.7        0.65277778
 0.67222222 0.7        0.65277778 0.67222222 0.7        0.65277778
 0.67222222 0.7        0.65277778 0.67222222 0.7        0.65277778
 0.67222222 0.7        0.65277778 0.67222222 0.7        0.65277778]

 **examine the best model 

0.7194444444444444
{'C': 0.01, 'gamma': 0.001, 'kernel': 'linear'}
SVC(C=0.01, gamma=0.001, kernel='linear')


In [21]:
from sklearn import svm
svm= svm.SVC(random_state = 1, C = bestS_['C'], gamma = bestS_['gamma'], kernel = bestS_['kernel'])
modelOpt = svm.fit(X_train, y_train)


y_pred = modelOpt.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.67      1.00      0.80         4
           1       1.00      0.75      0.86         8

    accuracy                           0.83        12
   macro avg       0.83      0.88      0.83        12
weighted avg       0.89      0.83      0.84        12

[[4 0]
 [2 6]]


##Mean fv- Normalization

In [22]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

X_train_norm = np.linalg.norm(X_train)
X_train_norm = X_train/X_train_norm

X_test_norm = np.linalg.norm(X_test)
X_test_norm = X_test/X_test_norm

In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

Cs = [0.001, 0.01, 0.1, 1, 10]
gammas = [0.001, 0.01, 0.1, 1]
kernels = ['linear', 'rbf', 'poly']

svm= svm.SVC()
param_grid = {'C': Cs, 'gamma' : gammas, 'kernel' : kernels}
grid_search = GridSearchCV(svm, param_grid, cv=5)

SVM = grid_search.fit(X_train_norm, y_train)

# examine the first result
print("**examine the first result","\n")

print(SVM.cv_results_['params'][0])
print(SVM.cv_results_['mean_test_score'][0])

# print the array of mean scores only
print("\n","**print the array of mean scores only","\n")

grid_mean_scores = SVM.cv_results_['mean_test_score']
print(grid_mean_scores)

# examine the best model
print("\n","**examine the best model","\n")
bestS_ = SVM.best_params_
print(SVM.best_score_)
print(SVM.best_params_)
print(SVM.best_estimator_)

**examine the first result 

{'C': 0.001, 'gamma': 0.001, 'kernel': 'linear'}
0.7

 **print the array of mean scores only 

[0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7
 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7
 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7
 0.7 0.7 0.7 0.7 0.7 0.7]

 **examine the best model 

0.7
{'C': 0.001, 'gamma': 0.001, 'kernel': 'linear'}
SVC(C=0.001, gamma=0.001, kernel='linear')


In [24]:
from sklearn import svm
svm= svm.SVC(random_state = 1, C = bestS_['C'], gamma = bestS_['gamma'], kernel = bestS_['kernel'])
modelOpt = svm.fit(X_train_norm, y_train)

y_pred = modelOpt.predict(X_test_norm)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.67      1.00      0.80         8

    accuracy                           0.67        12
   macro avg       0.33      0.50      0.40        12
weighted avg       0.44      0.67      0.53        12

[[0 4]
 [0 8]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 5️⃣ ML // DT Classifier

## Mean fv

In [25]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

In [26]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#Setup the parameters and distributions to sample from : param_dist
param_dist  = {'min_samples_split': [2, 4, 6, 10],
                      'min_samples_leaf': [1, 2, 4, 10],
                      'max_depth': [None, 4, 10],
                      'splitter' : ('best', 'random'),
                      'max_features':[None, 2, 4, 6],
                      'class_weight':[{0: w} for w in [1, 2, 4]]}
#Instantiate a Decision Tree classifier: tree
tree = DecisionTreeClassifier()

#Instantiate the RandomizedSearchCV object: tree_cv
tree_cv = GridSearchCV(tree, param_dist , cv =5)

#Fit it to the data
tree_cv.fit(X_train,y_train )


# examine the first result
print("**examine the first result","\n")

print(tree_cv.cv_results_['params'][0])
print(tree_cv.cv_results_['mean_test_score'][0])

# print the array of mean scores only
print("\n","**print the array of mean scores only","\n")

grid_mean_scores = tree_cv.cv_results_['mean_test_score']
print(grid_mean_scores)

# examine the best model
print("\n","**examine the best model","\n")

print(tree_cv.best_score_)
print(tree_cv.best_params_)
print(tree_cv.best_estimator_)

bestT_ = tree_cv.best_params_

#Print the tured parameters and score
print("Tuned Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))

#Hyperparameter
tree =  DecisionTreeClassifier(criterion = 'entropy',
                               class_weight = bestT_['class_weight'],
                               max_depth = bestT_['max_depth'],
                               max_features =bestT_['max_features'],
                               min_samples_leaf = bestT_['min_samples_leaf'],
                               min_samples_split = bestT_['min_samples_split'],
                               splitter = bestT_['splitter'] )
tree_cv = tree.fit(X_train, y_train)

#Predicting the Test set results
y_pred = tree_cv.predict(X_test)

#Marking the Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))#performance

**examine the first result 

{'class_weight': {0: 1}, 'max_depth': None, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'best'}
0.6722222222222223

 **print the array of mean scores only 

[0.67222222 0.58333333 0.65       ... 0.37222222 0.48611111 0.45833333]

 **examine the best model 

0.8166666666666667
{'class_weight': {0: 1}, 'max_depth': 4, 'max_features': 6, 'min_samples_leaf': 4, 'min_samples_split': 6, 'splitter': 'random'}
DecisionTreeClassifier(class_weight={0: 1}, max_depth=4, max_features=6,
                       min_samples_leaf=4, min_samples_split=6,
                       splitter='random')
Tuned Decision Tree Parameters: {'class_weight': {0: 1}, 'max_depth': 4, 'max_features': 6, 'min_samples_leaf': 4, 'min_samples_split': 6, 'splitter': 'random'}
Best score is 0.8166666666666667
[[3 1]
 [4 4]]
              precision    recall  f1-score   support

           0       0.43      0.75      0.55         4
           1       0.80      0.

## Mean fv- Normalization

In [27]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

X_train_norm = np.linalg.norm(X_train)
X_train_norm = X_train/X_train_norm

X_test_norm = np.linalg.norm(X_test)
X_test_norm = X_test/X_test_norm

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#Setup the parameters and distributions to sample from : param_dist
param_dist  = {'min_samples_split': [2, 4, 6, 10],
                      'min_samples_leaf': [1, 2, 4, 10],
                      'max_depth': [None, 4, 10],
                      'splitter' : ('best', 'random'),
                      'max_features':[None, 2, 4, 6],
                      'class_weight':[{0: w} for w in [1, 2, 4]]}
#Instantiate a Decision Tree classifier: tree
tree = DecisionTreeClassifier()

#Instantiate the RandomizedSearchCV object: tree_cv
tree_cv = GridSearchCV(tree, param_dist , cv =5)

#Fit it to the data
tree_cv.fit(X_train_norm,y_train )


# examine the first result
print("**examine the first result","\n")

print(tree_cv.cv_results_['params'][0])
print(tree_cv.cv_results_['mean_test_score'][0])

# print the array of mean scores only
print("\n","**print the array of mean scores only","\n")

grid_mean_scores = tree_cv.cv_results_['mean_test_score']
print(grid_mean_scores)

# examine the best model
print("\n","**examine the best model","\n")

print(tree_cv.best_score_)
print(tree_cv.best_params_)
print(tree_cv.best_estimator_)

bestT_ = tree_cv.best_params_

#Print the tured parameters and score
print("Tuned Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))

#Hyperparameter
tree =  DecisionTreeClassifier(criterion = 'entropy',
                               class_weight = bestT_['class_weight'],
                               max_depth = bestT_['max_depth'],
                               max_features =bestT_['max_features'],
                               min_samples_leaf = bestT_['min_samples_leaf'],
                               min_samples_split = bestT_['min_samples_split'],
                               splitter = bestT_['splitter'] )
tree_cv = tree.fit(X_train_norm, y_train)

#Predicting the Test set results
y_pred = tree_cv.predict(X_test_norm)

#Marking the Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))#performance

**examine the first result 

{'class_weight': {0: 1}, 'max_depth': None, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'best'}
0.6722222222222223

 **print the array of mean scores only 

[0.67222222 0.675      0.62777778 ... 0.3        0.37777778 0.3       ]

 **examine the best model 

0.8333333333333333
{'class_weight': {0: 2}, 'max_depth': 10, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 4, 'splitter': 'best'}
DecisionTreeClassifier(class_weight={0: 2}, max_depth=10, min_samples_split=4)
Tuned Decision Tree Parameters: {'class_weight': {0: 2}, 'max_depth': 10, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 4, 'splitter': 'best'}
Best score is 0.8333333333333333
[[1 3]
 [1 7]]
              precision    recall  f1-score   support

           0       0.50      0.25      0.33         4
           1       0.70      0.88      0.78         8

    accuracy                           0.67        12
   macro avg      

# 6️⃣ ML // KNN Classifier

## Mean fv

In [29]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

In [30]:
from sklearn.neighbors import KNeighborsClassifier

# data = list(zip(x, y))
knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

#Marking the Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))#performance

[[2 2]
 [1 7]]
              precision    recall  f1-score   support

           0       0.67      0.50      0.57         4
           1       0.78      0.88      0.82         8

    accuracy                           0.75        12
   macro avg       0.72      0.69      0.70        12
weighted avg       0.74      0.75      0.74        12



## Mean fv- Normalization

In [31]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

X_train_norm = np.linalg.norm(X_train)
X_train_norm = X_train/X_train_norm

X_test_norm = np.linalg.norm(X_test)
X_test_norm = X_test/X_test_norm

In [32]:
from sklearn.neighbors import KNeighborsClassifier

# data = list(zip(x, y))
knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train_norm, y_train)

y_pred = knn.predict(X_test_norm)

#Marking the Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))#performance

[[0 4]
 [0 8]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.67      1.00      0.80         8

    accuracy                           0.67        12
   macro avg       0.33      0.50      0.40        12
weighted avg       0.44      0.67      0.53        12



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
