<a href="https://colab.research.google.com/github/Anusarakh/thesis/blob/main/16_01_24_FV_ML_DEMO_Version.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1️⃣ เชื่อม google drive

In [22]:
#เชื่อม google drive
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [23]:
#เข้าไป path ใน google drive
import os
os.chdir('/content/gdrive/MyDrive/Thesis/music/')

!pwd #เช็ค paht ที่กำลังทำงานอยู่

/content/gdrive/MyDrive/Thesis/music


# 2️⃣ Data preparation by FV

In [24]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
import csv
import scipy.io.wavfile as wav

In [25]:
classes_1 = 1
classes_0 = 0

path_1 = '/content/gdrive/MyDrive/Thesis/music/nontherapy/'
path_0 = '/content/gdrive/MyDrive/Thesis/music/fortherapy/'

In [28]:
x_list = os.listdir(path_0)
mfcc_mean_0 = []
#mfcc_var_0 = []
spec_cen_mean_0 = []
#spec_cen_var_0 = []
spec_band_mean_0 = []
#spec_band_var_0 = []
zcr_mean_0 = []
#zcr_var_0 = []
tempo = []
classes_0_ = []
tempo_0 = []
for i in x_list:
  x , sr = librosa.load(path_0+i, sr=44100)
  #สกัด MFCC
  mfcc = librosa.feature.mfcc(y=x, sr=44100 ,n_mfcc= 20, n_fft = 512,  hop_length=256 )
  df_mfcc = pd.DataFrame(mfcc)
  mfcc_mean = df_mfcc.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล MFCC
  #mfcc_var= df_mfcc.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล MFCC
  #สกัด spectral_centroid
  spec_cen = librosa.feature.spectral_centroid(y=x, sr=44100, S=None, n_fft=512, hop_length=256)
  df_spec_cen = pd.DataFrame(spec_cen)
  spec_cen_mean = df_spec_cen.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล spectral_centroid
  #spec_cen_var= df_spec_cen.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล spectral_centroid
  #สกัด spectral_bandwidth
  spec_band = librosa.feature.spectral_bandwidth(y=x, sr=44100, S=None, n_fft=512, hop_length=256)
  df_spec_band = pd.DataFrame(spec_band)
  spec_band_mean = df_spec_band.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล spectral_bandwidth
  #spec_band_var= df_spec_band.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล spectral_bandwidth
  #สกัด zero_crossing_rate
  zcr = librosa.feature.zero_crossing_rate(y=x, frame_length=512, hop_length=256)
  df_zcr = pd.DataFrame(zcr)
  zcr_mean = df_zcr.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล zero_crossing_rate
  #zcr_var= df_zcr.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล zero_crossing_rate
  #สกัด tempo
  tempo = librosa.feature.tempo(y=x, sr=44100 , hop_length=256)

  mfcc_mean_0.append(list(mfcc_mean))
  #mfcc_var_0.append(list(mfcc_var))
  spec_cen_mean_0.append(spec_cen_mean[0])
  #spec_cen_var_0.append(spec_cen_var[0])
  spec_band_mean_0.append(spec_band_mean[0])
  #spec_band_var_0.append(spec_band_var[0])
  zcr_mean_0.append(zcr_mean[0])
  #zcr_var_0.append(zcr_var[0])
  tempo_0.append(tempo[0])

  classes_0_.append(path_0+i)

In [27]:
x_list = os.listdir(path_1)
mfcc_mean_1 = []
#mfcc_var_1 = []
spec_cen_mean_1 = []
#spec_cen_var_1 = []
spec_band_mean_1 = []
#spec_band_var_1 = []
zcr_mean_1 = []
#zcr_var_1 = []
tempo = []
classes_1_ = []
tempo_1 = []
for i in x_list:
  x , sr = librosa.load(path_1+i, sr=44100)
  #สกัด MFCC
  mfcc = librosa.feature.mfcc(y=x, sr=44100 ,n_mfcc= 20, n_fft = 512,  hop_length=256 )
  df_mfcc = pd.DataFrame(mfcc)
  mfcc_mean = df_mfcc.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล MFCC
  #mfcc_var= df_mfcc.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล MFCC
  #สกัด spectral_centroid
  spec_cen = librosa.feature.spectral_centroid(y=x, sr=44100, S=None, n_fft=512, hop_length=256)
  df_spec_cen = pd.DataFrame(spec_cen)
  spec_cen_mean = df_spec_cen.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล spectral_centroid
  #spec_cen_var= df_spec_cen.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล spectral_centroid
  #สกัด spectral_bandwidth
  spec_band = librosa.feature.spectral_bandwidth(y=x, sr=44100, S=None, n_fft=512, hop_length=256)
  df_spec_band = pd.DataFrame(spec_band)
  spec_band_mean = df_spec_band.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล spectral_bandwidth
  #spec_band_var= df_spec_band.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล spectral_bandwidth
  #สกัด zero_crossing_rate
  zcr = librosa.feature.zero_crossing_rate(y=x, frame_length=512, hop_length=256)
  df_zcr = pd.DataFrame(zcr)
  zcr_mean = df_zcr.mean(axis = 1) #หาค่าเฉลี่ยในแต่ละลำดับข้อมูล zero_crossing_rate
  #zcr_var= df_zcr.var(axis = 1) #หาค่าความแปรปรวนในแต่ละลำดับข้อมูล zero_crossing_rate
  #สกัด tempo
  tempo = librosa.feature.tempo(y=x, sr=44100, hop_length=256)


  mfcc_mean_1.append(list(mfcc_mean))
  #mfcc_var_1.append(list(mfcc_var))
  spec_cen_mean_1.append(spec_cen_mean[0])
  #spec_cen_var_1.append(spec_cen_var[0])
  spec_band_mean_1.append(spec_band_mean[0])
  #spec_band_var_1.append(spec_band_var[0])
  zcr_mean_1.append(zcr_mean[0])
  #zcr_var_1.append(zcr_var[0])
  tempo_1.append(tempo[0])

  classes_1_.append(path_1+i)

<ipython-input-27-c75411cd6c68>:14: UserWarning: PySoundFile failed. Trying audioread instead.
  x , sr = librosa.load(path_1+i, sr=44100)
/usr/local/lib/python3.10/dist-packages/librosa/feature/spectral.py:2143: UserWarning: Empty filters detected in mel frequency basis. Some channels will produce empty responses. Try increasing your sampling rate (and fmax) or reducing n_mels.
  mel_basis = filters.mel(sr=sr, n_fft=n_fft, **kwargs)
<ipython-input-27-c75411cd6c68>:14: UserWarning: PySoundFile failed. Trying audioread instead.
  x , sr = librosa.load(path_1+i, sr=44100)
/usr/local/lib/python3.10/dist-packages/librosa/core/audio.py:183: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
/usr/local/lib/python3.10/dist-packages/librosa/feature/spectral.py:2143: UserWarning: Empty filters detected in mel frequency basis. Some channels will p

In [29]:
mfcc_mean_0 = np.array(mfcc_mean_0)
mfcc_mean_1 = np.array(mfcc_mean_1)

mfcc_mean_df = pd.DataFrame(data = mfcc_mean_0)
mfcc_mean_df['spec'] = spec_cen_mean_0
mfcc_mean_df['specband'] = spec_band_mean_0
mfcc_mean_df['zero'] = zcr_mean_0
mfcc_mean_df['tempo'] = tempo_0
mfcc_mean_df['y'] = 0
mfcc_mean_df['path'] = classes_0_

mfcc_mean_df_1 = pd.DataFrame(data = mfcc_mean_1)
mfcc_mean_df_1['spec'] = spec_cen_mean_1
mfcc_mean_df_1['specband'] = spec_band_mean_1
mfcc_mean_df_1['zero'] = zcr_mean_1
mfcc_mean_df_1['tempo'] = tempo_1
mfcc_mean_df_1['y'] = 1
mfcc_mean_df_1['path'] = classes_1_

df_mean = mfcc_mean_df.append(mfcc_mean_df_1)

print(df_mean.shape)
df_mean.head()

(117, 26)


<ipython-input-29-8ce7a2c1c5a2>:20: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_mean = mfcc_mean_df.append(mfcc_mean_df_1)


0           1          2          3          4          5  \
0 -379.508820   67.611938 -62.423706  23.165838 -17.030453  33.050392   
1 -354.847870   87.174637 -31.676809  11.795785   1.417268  23.362387   
2 -242.735413   84.182892 -89.690178  33.847168 -10.871581  36.350422   
3 -392.375122   88.908119 -23.111881  28.746162  -3.523097  25.930311   
4 -463.481934  124.672264 -41.370480  13.227163 -16.169811  28.671621   

           6          7          8          9  ...        16        17  \
0 -18.436098  15.426235 -15.747377   3.422516  ...  0.365399 -2.700605   
1 -12.640376  10.996572 -12.979669  -4.319019  ... -2.025934 -1.024250   
2 -14.858019  12.861016 -17.039759  -3.613929  ...  3.280125 -6.115852   
3  -2.549639   4.360907  -8.801807  -5.679143  ... -2.242397 -1.934690   
4 -10.807143  -1.309174  -7.763828 -11.823654  ... -3.239670  1.940748   

         18        19         spec     specband      zero       tempo  y  \
0  4.046536 -3.121535  3388.793306  3738.388161  0.081786  124.529367  0   
1  4.028388 -4.888572  2310.175751  3085.561672  0.050950  121.599265  0   
2  3.467003 -0.075818  2829.275712  3050.874501  0.077162  107.666016  0   
3  1.106406 -1.754013  1927.390737  2802.790943  0.037422  135.999178  0   
4  1.754940  1.806270  1548.013281  2312.849218  0.036935  111.139113  0   

                                                path  
0  /content/gdrive/MyDrive/Thesis/music/fortherap...  
1  /content/gdrive/MyDrive/Thesis/music/fortherap...  
2  /content/gdrive/MyDrive/Thesis/music/fortherap...  
3  /content/gdrive/MyDrive/Thesis/music/fortherap...  
4  /content/gdrive/MyDrive/Thesis/music/fortherap...  

[5 rows x 26 columns]

In [30]:
#mfcc_var_0 = np.array(mfcc_var_0)
#mfcc_var_1 = np.array(mfcc_var_1)

#mfcc_var_df = pd.DataFrame(data = mfcc_var_0)
#mfcc_var_df['spec'] = spec_cen_var_0
#mfcc_var_df['specband'] = spec_band_var_0
#mfcc_var_df['zero'] = zcr_var_0
#mfcc_var_df['tempo'] = tempo_0
#mfcc_var_df['y'] = 0
#mfcc_var_df['path'] = classes_0_

#mfcc_var_df_1 = pd.DataFrame(data = mfcc_var_1)
#mfcc_var_df_1['spec'] = spec_cen_var_1
#mfcc_var_df_1['specband'] = spec_band_var_1
#mfcc_var_df_1['zero'] = zcr_var_1
#mfcc_var_df_1['tempo'] = tempo_1
#mfcc_var_df_1['y'] = 1
#mfcc_var_df_1['path'] = classes_1_

#df_var = mfcc_var_df.append(mfcc_var_df_1)

#print(df_var.shape)
#df_var.head()

## Split data train/teast by 80:20

In [31]:
df_mean.head()

0           1          2          3          4          5  \
0 -379.508820   67.611938 -62.423706  23.165838 -17.030453  33.050392   
1 -354.847870   87.174637 -31.676809  11.795785   1.417268  23.362387   
2 -242.735413   84.182892 -89.690178  33.847168 -10.871581  36.350422   
3 -392.375122   88.908119 -23.111881  28.746162  -3.523097  25.930311   
4 -463.481934  124.672264 -41.370480  13.227163 -16.169811  28.671621   

           6          7          8          9  ...        16        17  \
0 -18.436098  15.426235 -15.747377   3.422516  ...  0.365399 -2.700605   
1 -12.640376  10.996572 -12.979669  -4.319019  ... -2.025934 -1.024250   
2 -14.858019  12.861016 -17.039759  -3.613929  ...  3.280125 -6.115852   
3  -2.549639   4.360907  -8.801807  -5.679143  ... -2.242397 -1.934690   
4 -10.807143  -1.309174  -7.763828 -11.823654  ... -3.239670  1.940748   

         18        19         spec     specband      zero       tempo  y  \
0  4.046536 -3.121535  3388.793306  3738.388161  0.081786  124.529367  0   
1  4.028388 -4.888572  2310.175751  3085.561672  0.050950  121.599265  0   
2  3.467003 -0.075818  2829.275712  3050.874501  0.077162  107.666016  0   
3  1.106406 -1.754013  1927.390737  2802.790943  0.037422  135.999178  0   
4  1.754940  1.806270  1548.013281  2312.849218  0.036935  111.139113  0   

                                                path  
0  /content/gdrive/MyDrive/Thesis/music/fortherap...  
1  /content/gdrive/MyDrive/Thesis/music/fortherap...  
2  /content/gdrive/MyDrive/Thesis/music/fortherap...  
3  /content/gdrive/MyDrive/Thesis/music/fortherap...  
4  /content/gdrive/MyDrive/Thesis/music/fortherap...  

[5 rows x 26 columns]

In [32]:
path = df_mean[df_mean['y']== 0]['path'].tolist()
# print(len(path))
from random import sample
res_samle_0 = sample(path,int(len(path)*0.8))
print(len(set(res_samle_0)))

path = df_mean[df_mean['y']== 1]['path'].tolist()
# print(len(path))
from random import sample
res_samle_1 = sample(path,int(len(path)*0.8))
print(len(set(res_samle_1)))

res_samle_0.extend(res_samle_1)

print(len(res_samle_0))

28
65
93


In [33]:
train = df_mean[df_mean['path'].isin(res_samle_0)]
train['split'] = 'train'
test = df_mean[~df_mean['path'].isin(res_samle_0)]
test['split'] = 'test'

df_all = train.append(test)
print(df_all.shape)
df_all.head()

(117, 27)


<ipython-input-33-d13c214b5ed7>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['split'] = 'train'
<ipython-input-33-d13c214b5ed7>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['split'] = 'test'
<ipython-input-33-d13c214b5ed7>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_all = train.append(test)


0          1          2          3          4          5  \
0 -379.508820  67.611938 -62.423706  23.165838 -17.030453  33.050392   
1 -354.847870  87.174637 -31.676809  11.795785   1.417268  23.362387   
2 -242.735413  84.182892 -89.690178  33.847168 -10.871581  36.350422   
3 -392.375122  88.908119 -23.111881  28.746162  -3.523097  25.930311   
5 -343.581726  94.486427 -31.478441  14.653499 -18.981001  29.790760   

           6          7          8         9  ...        17        18  \
0 -18.436098  15.426235 -15.747377  3.422516  ... -2.700605  4.046536   
1 -12.640376  10.996572 -12.979669 -4.319019  ... -1.024250  4.028388   
2 -14.858019  12.861016 -17.039759 -3.613929  ... -6.115852  3.467003   
3  -2.549639   4.360907  -8.801807 -5.679143  ... -1.934690  1.106406   
5 -13.614028   6.838835 -15.953328 -8.611911  ... -6.815122  4.428864   

         19         spec     specband      zero       tempo  y  \
0 -3.121535  3388.793306  3738.388161  0.081786  124.529367  0   
1 -4.888572  2310.175751  3085.561672  0.050950  121.599265  0   
2 -0.075818  2829.275712  3050.874501  0.077162  107.666016  0   
3 -1.754013  1927.390737  2802.790943  0.037422  135.999178  0   
5 -1.874795  2375.826008  3245.419077  0.049871  120.185320  0   

                                                path  split  
0  /content/gdrive/MyDrive/Thesis/music/fortherap...  train  
1  /content/gdrive/MyDrive/Thesis/music/fortherap...  train  
2  /content/gdrive/MyDrive/Thesis/music/fortherap...  train  
3  /content/gdrive/MyDrive/Thesis/music/fortherap...  train  
5  /content/gdrive/MyDrive/Thesis/music/fortherap...  train  

[5 rows x 27 columns]

In [34]:
# var fv same table
#df_var['split'] = df_var['path'].map(df_all.set_index('path')['split']) # can map column split by path column
#df_var.head()

# 3️⃣ ML// Random Forest Classifier

In [35]:
# X_train

In [36]:
import os
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

## Mean fv

In [37]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

n_estimators = [400]
max_depth = [5, 8, 15, 25, 30]
min_samples_split = [2, 5, 10, 15, 100]
forest = RandomForestClassifier(random_state = 1)
hyperF ={'n_estimators' : n_estimators, 'max_depth' : max_depth, 'min_samples_split' : min_samples_split}
gridF = GridSearchCV(forest, hyperF, cv = 3, verbose = 1, n_jobs = -1)
bestF = gridF.fit(X_train, y_train)
bestF_ = bestF.best_params_

forestOpt = RandomForestClassifier(random_state = 1, max_depth = bestF_['max_depth'], n_estimators = bestF_['n_estimators'], min_samples_split =bestF_['min_samples_split'])
modelOpt = forestOpt.fit(X_train, y_train)

print(bestF_)

Fitting 3 folds for each of 25 candidates, totalling 75 fits
{'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 400}


In [38]:
y_pred = modelOpt.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.50      0.43      0.46         7
           1       0.78      0.82      0.80        17

    accuracy                           0.71        24
   macro avg       0.64      0.63      0.63        24
weighted avg       0.70      0.71      0.70        24

[[ 3  4]
 [ 3 14]]


## Mean fv- Normalization

In [39]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

X_train_norm = np.linalg.norm(X_train)
X_train_norm = X_train/X_train_norm

X_test_norm = np.linalg.norm(X_test)
X_test_norm = X_test/X_test_norm


n_estimators = [400, 500, 1000, 1500]
max_depth = [5, 8, 15, 25, 30]
min_samples_split = [2, 5, 10, 15, 100]
forest = RandomForestClassifier(random_state = 1)
hyperF ={'n_estimators' : n_estimators, 'max_depth' : max_depth, 'min_samples_split' : min_samples_split}
gridF = GridSearchCV(forest, hyperF, cv = 3, verbose = 1, n_jobs = -1)
bestF = gridF.fit(X_train_norm, y_train)
bestF_ = bestF.best_params_

forestOpt = RandomForestClassifier(random_state = 1, max_depth = bestF_['max_depth'], n_estimators = bestF_['n_estimators'], min_samples_split =bestF_['min_samples_split'])
modelOpt = forestOpt.fit(X_train_norm, y_train)

print(bestF_)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
{'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 400}


In [40]:
y_pred = modelOpt.predict(X_test_norm)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.29      1.00      0.45         7
           1       0.00      0.00      0.00        17

    accuracy                           0.29        24
   macro avg       0.15      0.50      0.23        24
weighted avg       0.09      0.29      0.13        24

[[ 7  0]
 [17  0]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 4️⃣ ML // SVM Classifier

## Mean fv

In [41]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

In [42]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

Cs = [0.001, 0.01, 0.1, 1, 10]
gammas = [0.001, 0.01, 0.1, 1]
kernels = ['linear', 'rbf', 'poly']

svm= svm.SVC()
param_grid = {'C': Cs, 'gamma' : gammas, 'kernel' : kernels}
grid_search = GridSearchCV(svm, param_grid, cv=5)

SVM = grid_search.fit(X_train, y_train)

# examine the first result
print("**examine the first result","\n")

print(SVM.cv_results_['params'][0])
print(SVM.cv_results_['mean_test_score'][0])

# print the array of mean scores only
print("\n","**print the array of mean scores only","\n")

grid_mean_scores = SVM.cv_results_['mean_test_score']
print(grid_mean_scores)

# examine the best model
print("\n","**examine the best model","\n")
bestS_ = SVM.best_params_
print(SVM.best_score_)
print(SVM.best_params_)
print(SVM.best_estimator_)

**examine the first result 

{'C': 0.001, 'gamma': 0.001, 'kernel': 'linear'}
0.7842105263157895

 **print the array of mean scores only 

[0.78421053 0.6994152  0.63274854 0.78421053 0.6994152  0.60116959
 0.78421053 0.6994152  0.57953216 0.78421053 0.6994152  0.58947368
 0.74152047 0.6994152  0.63274854 0.74152047 0.6994152  0.60116959
 0.74152047 0.6994152  0.57953216 0.74152047 0.6994152  0.58947368
 0.71871345 0.6994152  0.63274854 0.71871345 0.6994152  0.60116959
 0.71871345 0.6994152  0.57953216 0.71871345 0.6994152  0.58947368
 0.62339181 0.6994152  0.63274854 0.62339181 0.6994152  0.60116959
 0.62339181 0.6994152  0.57953216 0.62339181 0.6994152  0.58947368
 0.62339181 0.6994152  0.63274854 0.62339181 0.6994152  0.60116959
 0.62339181 0.6994152  0.57953216 0.62339181 0.6994152  0.58947368]

 **examine the best model 

0.7842105263157895
{'C': 0.001, 'gamma': 0.001, 'kernel': 'linear'}
SVC(C=0.001, gamma=0.001, kernel='linear')


In [43]:
from sklearn import svm
svm= svm.SVC(random_state = 1, C = bestS_['C'], gamma = bestS_['gamma'], kernel = bestS_['kernel'])
modelOpt = svm.fit(X_train, y_train)


y_pred = modelOpt.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.67      0.29      0.40         7
           1       0.76      0.94      0.84        17

    accuracy                           0.75        24
   macro avg       0.71      0.61      0.62        24
weighted avg       0.73      0.75      0.71        24

[[ 2  5]
 [ 1 16]]


##Mean fv- Normalization

In [44]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

X_train_norm = np.linalg.norm(X_train)
X_train_norm = X_train/X_train_norm

X_test_norm = np.linalg.norm(X_test)
X_test_norm = X_test/X_test_norm

In [45]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

Cs = [0.001, 0.01, 0.1, 1, 10]
gammas = [0.001, 0.01, 0.1, 1]
kernels = ['linear', 'rbf', 'poly']

svm= svm.SVC()
param_grid = {'C': Cs, 'gamma' : gammas, 'kernel' : kernels}
grid_search = GridSearchCV(svm, param_grid, cv=5)

SVM = grid_search.fit(X_train_norm, y_train)

# examine the first result
print("**examine the first result","\n")

print(SVM.cv_results_['params'][0])
print(SVM.cv_results_['mean_test_score'][0])

# print the array of mean scores only
print("\n","**print the array of mean scores only","\n")

grid_mean_scores = SVM.cv_results_['mean_test_score']
print(grid_mean_scores)

# examine the best model
print("\n","**examine the best model","\n")
bestS_ = SVM.best_params_
print(SVM.best_score_)
print(SVM.best_params_)
print(SVM.best_estimator_)

**examine the first result 

{'C': 0.001, 'gamma': 0.001, 'kernel': 'linear'}
0.6994152046783626

 **print the array of mean scores only 

[0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152
 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152
 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152
 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152
 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152
 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152
 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152
 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152 0.6994152
 0.6994152 0.6994152 0.6994152 0.6994152]

 **examine the best model 

0.6994152046783626
{'C': 0.001, 'gamma': 0.001, 'kernel': 'linear'}
SVC(C=0.001, gamma=0.001, kernel='linear')


In [46]:
from sklearn import svm
svm= svm.SVC(random_state = 1, C = bestS_['C'], gamma = bestS_['gamma'], kernel = bestS_['kernel'])
modelOpt = svm.fit(X_train_norm, y_train)

y_pred = modelOpt.predict(X_test_norm)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.71      1.00      0.83        17

    accuracy                           0.71        24
   macro avg       0.35      0.50      0.41        24
weighted avg       0.50      0.71      0.59        24

[[ 0  7]
 [ 0 17]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# 5️⃣ ML // DT Classifier

## Mean fv

In [47]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

In [48]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#Setup the parameters and distributions to sample from : param_dist
param_dist  = {'min_samples_split': [2, 4, 6, 10],
                      'min_samples_leaf': [1, 2, 4, 10],
                      'max_depth': [None, 4, 10],
                      'splitter' : ('best', 'random'),
                      'max_features':[None, 2, 4, 6],
                      'class_weight':[{0: w} for w in [1, 2, 4]]}
#Instantiate a Decision Tree classifier: tree
tree = DecisionTreeClassifier()

#Instantiate the RandomizedSearchCV object: tree_cv
tree_cv = GridSearchCV(tree, param_dist , cv =5)

#Fit it to the data
tree_cv.fit(X_train,y_train )


# examine the first result
print("**examine the first result","\n")

print(tree_cv.cv_results_['params'][0])
print(tree_cv.cv_results_['mean_test_score'][0])

# print the array of mean scores only
print("\n","**print the array of mean scores only","\n")

grid_mean_scores = tree_cv.cv_results_['mean_test_score']
print(grid_mean_scores)

# examine the best model
print("\n","**examine the best model","\n")

print(tree_cv.best_score_)
print(tree_cv.best_params_)
print(tree_cv.best_estimator_)

bestT_ = tree_cv.best_params_

#Print the tured parameters and score
print("Tuned Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))

#Hyperparameter
tree =  DecisionTreeClassifier(criterion = 'entropy',
                               class_weight = bestT_['class_weight'],
                               max_depth = bestT_['max_depth'],
                               max_features =bestT_['max_features'],
                               min_samples_leaf = bestT_['min_samples_leaf'],
                               min_samples_split = bestT_['min_samples_split'],
                               splitter = bestT_['splitter'] )
tree_cv = tree.fit(X_train, y_train)

#Predicting the Test set results
y_pred = tree_cv.predict(X_test)

#Marking the Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))#performance

**examine the first result 

{'class_weight': {0: 1}, 'max_depth': None, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'best'}
0.6766081871345029

 **print the array of mean scores only 

[0.67660819 0.75321637 0.6871345  ... 0.49707602 0.61345029 0.48479532]

 **examine the best model 

0.8385964912280702
{'class_weight': {0: 1}, 'max_depth': None, 'max_features': None, 'min_samples_leaf': 2, 'min_samples_split': 6, 'splitter': 'best'}
DecisionTreeClassifier(class_weight={0: 1}, min_samples_leaf=2,
                       min_samples_split=6)
Tuned Decision Tree Parameters: {'class_weight': {0: 1}, 'max_depth': None, 'max_features': None, 'min_samples_leaf': 2, 'min_samples_split': 6, 'splitter': 'best'}
Best score is 0.8385964912280702
[[ 6  1]
 [ 3 14]]
              precision    recall  f1-score   support

           0       0.67      0.86      0.75         7
           1       0.93      0.82      0.87        17

    accuracy                       

## Mean fv- Normalization

In [49]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

X_train_norm = np.linalg.norm(X_train)
X_train_norm = X_train/X_train_norm

X_test_norm = np.linalg.norm(X_test)
X_test_norm = X_test/X_test_norm

In [50]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#Setup the parameters and distributions to sample from : param_dist
param_dist  = {'min_samples_split': [2, 4, 6, 10],
                      'min_samples_leaf': [1, 2, 4, 10],
                      'max_depth': [None, 4, 10],
                      'splitter' : ('best', 'random'),
                      'max_features':[None, 2, 4, 6],
                      'class_weight':[{0: w} for w in [1, 2, 4]]}
#Instantiate a Decision Tree classifier: tree
tree = DecisionTreeClassifier()

#Instantiate the RandomizedSearchCV object: tree_cv
tree_cv = GridSearchCV(tree, param_dist , cv =5)

#Fit it to the data
tree_cv.fit(X_train_norm,y_train )


# examine the first result
print("**examine the first result","\n")

print(tree_cv.cv_results_['params'][0])
print(tree_cv.cv_results_['mean_test_score'][0])

# print the array of mean scores only
print("\n","**print the array of mean scores only","\n")

grid_mean_scores = tree_cv.cv_results_['mean_test_score']
print(grid_mean_scores)

# examine the best model
print("\n","**examine the best model","\n")

print(tree_cv.best_score_)
print(tree_cv.best_params_)
print(tree_cv.best_estimator_)

bestT_ = tree_cv.best_params_

#Print the tured parameters and score
print("Tuned Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))

#Hyperparameter
tree =  DecisionTreeClassifier(criterion = 'entropy',
                               class_weight = bestT_['class_weight'],
                               max_depth = bestT_['max_depth'],
                               max_features =bestT_['max_features'],
                               min_samples_leaf = bestT_['min_samples_leaf'],
                               min_samples_split = bestT_['min_samples_split'],
                               splitter = bestT_['splitter'] )
tree_cv = tree.fit(X_train_norm, y_train)

#Predicting the Test set results
y_pred = tree_cv.predict(X_test_norm)

#Marking the Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))#performance

**examine the first result 

{'class_weight': {0: 1}, 'max_depth': None, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'splitter': 'best'}
0.6333333333333334

 **print the array of mean scores only 

[0.63333333 0.62339181 0.75321637 ... 0.49415205 0.4625731  0.51637427]

 **examine the best model 

0.8391812865497077
{'class_weight': {0: 1}, 'max_depth': 4, 'max_features': None, 'min_samples_leaf': 2, 'min_samples_split': 4, 'splitter': 'best'}
DecisionTreeClassifier(class_weight={0: 1}, max_depth=4, min_samples_leaf=2,
                       min_samples_split=4)
Tuned Decision Tree Parameters: {'class_weight': {0: 1}, 'max_depth': 4, 'max_features': None, 'min_samples_leaf': 2, 'min_samples_split': 4, 'splitter': 'best'}
Best score is 0.8391812865497077
[[ 2  5]
 [ 2 15]]
              precision    recall  f1-score   support

           0       0.50      0.29      0.36         7
           1       0.75      0.88      0.81        17

    accuracy                

# 6️⃣ ML // KNN Classifier

## Mean fv

In [51]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

In [52]:
from sklearn.neighbors import KNeighborsClassifier

# data = list(zip(x, y))
knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

#Marking the Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))#performance

[[ 0  7]
 [ 0 17]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.71      1.00      0.83        17

    accuracy                           0.71        24
   macro avg       0.35      0.50      0.41        24
weighted avg       0.50      0.71      0.59        24



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Mean fv- Normalization

In [53]:
train = df_all[df_all['split'] =='train']
test = df_all[df_all['split'] !='train']
X_train = train.iloc[:, 0:24].to_numpy()
X_test = test.iloc[:, 0:24].to_numpy()
y_train = train.iloc[:, -3]
y_test = test.iloc[:, -3]

X_train_norm = np.linalg.norm(X_train)
X_train_norm = X_train/X_train_norm

X_test_norm = np.linalg.norm(X_test)
X_test_norm = X_test/X_test_norm

In [54]:
from sklearn.neighbors import KNeighborsClassifier

# data = list(zip(x, y))
knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train_norm, y_train)

y_pred = knn.predict(X_test_norm)

#Marking the Confusion Matrix
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))#performance

[[ 0  7]
 [ 0 17]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         7
           1       0.71      1.00      0.83        17

    accuracy                           0.71        24
   macro avg       0.35      0.50      0.41        24
weighted avg       0.50      0.71      0.59        24



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
