<a href="https://colab.research.google.com/github/Anusarakh/thesis/blob/main/music_Ex_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
import csv

In [2]:
y, sr = librosa.load(librosa.ex('libri1'))
mfcc_test = librosa.feature.mfcc(y=y, sr=44100, S=None, n_mfcc=20)

In [3]:
y

array([0.00037424, 0.00036333, 0.00024905, ..., 0.00101743, 0.0023917 ,
       0.00200722], dtype=float32)

In [6]:
mfccScaled = np.mean(mfcc_test.T, axis=0) #axis=0 คือทำงานในแนวคอลัมล์
mfccScaled

array([-276.66803  ,  161.87306  ,  -24.257978 ,   34.798256 ,
         10.438065 ,    2.7754219,   -7.935828 ,   12.72298  ,
          5.517527 ,    1.1601148,   -3.810489 ,   -5.310315 ,
         -7.7707624,  -12.147796 ,   -8.521856 ,   -6.415033 ,
         -1.157337 ,   -0.6646697,    1.4520893,   -3.2086906],
      dtype=float32)

In [7]:
df_mfccScaled = pd.DataFrame(mfccScaled)
df_mfccScaled

0
0  -276.668030
1   161.873062
2   -24.257978
3    34.798256
4    10.438065
5     2.775422
6    -7.935828
7    12.722980
8     5.517527
9     1.160115
10   -3.810489
11   -5.310315
12   -7.770762
13  -12.147796
14   -8.521856
15   -6.415033
16   -1.157337
17   -0.664670
18    1.452089
19   -3.208691

In [4]:
len(y)

327222

In [5]:
df_ = pd.DataFrame(mfcc_test)
df_

0           1           2           3           4           5    \
0  -580.563782 -579.043213 -578.655518 -574.975403 -568.155457 -563.104309   
1    14.942307   16.862049   16.191315   20.091843   28.848083   36.064285   
2    13.763187   15.147621   11.621872   12.518572   19.190315   26.360775   
3    12.584791   13.479251    7.308465    5.555863   10.279902   16.769608   
4    11.935865   12.662352    5.671687    3.335501    7.393722   12.366469   
5    11.786961   12.664164    6.987242    6.330148   11.171232   14.222211   
6    11.592858   12.668779    9.313227   11.276693   17.454338   18.989939   
7    10.744301   11.749119   10.028494   13.789093   20.565689   21.560665   
8     9.069759    9.623350    7.786139   11.569662   17.438454   18.743156   
9     6.989947    6.899542    3.427038    5.822505    9.541170   11.304214   
10    5.204023    4.618204   -0.760768    0.001913    1.389886    3.051821   
11    4.157882    3.456403   -2.787563   -2.905383   -2.940869   -2.129660   
12    3.715788    3.222559   -2.351731   -2.392667   -2.551635   -2.967891   
13    3.294033    3.038860   -0.868704   -0.346163    0.206085   -1.287217   
14    2.348110    2.064330   -0.228620    0.776641    2.008159   -0.161406   
15    0.825368    0.184959   -1.327879   -0.133412    1.152633   -1.363110   
16   -0.775926   -1.874985   -3.509753   -2.297437   -1.533782   -4.128368   
17   -1.787178   -3.108542   -5.257618   -4.069028   -3.898047   -6.071257   
18   -1.887963   -3.010566   -5.483588   -4.431328   -4.475768   -5.343234   
19   -1.352437   -1.973576   -4.342721   -3.672975   -3.558012   -2.216679   

           6           7           8           9    ...         630  \
0  -569.086304 -575.819336 -580.513916 -583.474976  ... -298.780151   
1    29.632799   20.243217   13.979107   10.379160  ...  200.579620   
2    24.533577   15.432577   10.216854    8.124254  ...   -3.430164   
3    18.766636    9.928635    6.190442    5.859468  ...   14.526033   
4    14.633381    6.067735    3.822276    4.702595  ...   20.570446   
5    13.034028    5.134626    3.899349    4.849620  ...    8.954658   
6    13.171606    6.851991    5.760449    5.551494  ...   -1.961146   
7    13.363205    9.740936    7.882412    5.774958  ...   14.692663   
8    12.284746   12.031054    8.890132    4.999216  ...   15.166485   
9     9.744791   12.534420    8.293473    3.528960  ...    2.780458   
10    6.524787   11.031198    6.531971    2.121915  ...   -6.001768   
11    3.561963    8.096720    4.441530    1.287839  ...  -19.439865   
12    1.209858    4.637725    2.635882    0.864099  ...   -7.641262   
13   -0.840803    1.483308    1.260414    0.218388  ...   -8.601791   
14   -2.999443   -0.795965    0.202370   -1.108664  ...  -18.639339   
15   -5.134409   -1.899323   -0.543062   -2.883755  ...   -9.892307   
16   -6.466211   -1.790312   -0.739011   -4.251328  ...   -2.923307   
17   -6.136635   -0.738188   -0.138822   -4.373020  ...    9.144077   
18   -4.000320    0.678549    1.144185   -3.133708  ...    5.288239   
19   -0.960576    1.731579    2.507824   -1.332142  ...   -8.529924   

           631         632         633         634         635         636  \
0  -348.419098 -409.945984 -459.451263 -472.340942 -483.382996 -462.628693   
1   189.327423  155.025467  112.008667   94.525070   87.141701   92.656128   
2    26.567619   42.077988   32.277191   23.629436   23.060539    3.879772   
3    28.748602   44.746460   38.040031   34.573128   37.558231   31.760437   
4    37.111168   42.706284   40.391708   35.173561   40.495567   46.711601   
5    10.187418    3.810347   18.359224   15.453938   14.372238   12.705879   
6   -11.351871   -8.624639    8.155287    5.031083    4.187399    0.580451   
7    15.282798   19.655682   18.318865   18.902920   22.228121   22.726883   
8    10.705410   11.788424    3.870145    8.993621   16.081329   12.654745   
9    -2.537200   -7.650374  -12.277519   -3.733739    3.022994   -6.254004   
10    6.383070   -0.48

In [6]:
mfcc_mean = mfcc_test.mean()
mfcc_mean

-6.3565636

In [8]:
zcr = librosa.feature.zero_crossing_rate(y)
zcr

zcrScaled = np.mean(zcr.T, axis=0) #axis=0 คือทำงานในแนวคอลัมล์
zcrScaled

array([0.05833511])

In [8]:
df_zero = pd.DataFrame(zcr)
df_zero

0         1         2         3         4        5        6    \
0  0.029297  0.046875  0.056641  0.054199  0.041504  0.03125  0.03125   

        7        8         9    ...       630       631       632       633  \
0  0.040039  0.05957  0.069824  ...  0.022461  0.019043  0.016602  0.017578   

        634       635      636       637       638       639  
0  0.016602  0.035645  0.05127  0.064453  0.066895  0.043457  

[1 rows x 640 columns]

In [9]:
zcr_mean = zcr.mean()
zcr_mean

0.05833511352539063

In [10]:
import matplotlib.pyplot as plt
import scipy

In [11]:
lpc_test = librosa.lpc(y, order=1, axis=-1)
lpc_test

array([ 1.       , -0.9879697], dtype=float32)

In [12]:
df_lpc_test = pd.DataFrame(lpc_test)
df_lpc_test

0
0  1.00000
1 -0.98797

In [13]:
lpc_test_mean = lpc_test.mean()
lpc_test_mean

0.0060151517

In [14]:
spec_cent = librosa.feature.spectral_centroid(y=y, sr=sr)
spec_cent

array([[1948.53353543, 2065.75323454, 2108.69876753, 1940.67974686,
        1432.97012779, 1220.54620448, 1424.06811688, 1878.26750961,
        2019.98083004, 2392.98583544, 2143.85684057, 1773.82589143,
        1414.4036827 ,  977.48092965,  478.65798467,  555.13839594,
         675.54403021,  666.94888272,  641.9794709 , 1641.02501568,
        2182.31101546, 1040.99756461,  666.74507808,  701.19562093,
         658.53126068,  556.41104492,  484.02689886,  409.69151355,
         362.55139566,  360.07805904,  418.70314748,  547.45730946,
         639.73801207,  639.82683927,  598.56218605,  633.54585978,
         725.6159755 ,  677.06635433,  580.36914101,  694.17553202,
         850.27198308, 1421.56952594, 1316.58107483, 1263.50715845,
        1095.54530615,  818.65173713,  832.01570854,  871.74222318,
         859.26670021,  774.52719562,  714.90333639,  621.49940042,
         484.68363235,  407.88364609, 1217.12929656, 1386.54852844,
        1074.97338673,  771.66860782, 1027.09485

In [15]:
spec_cent_mean = spec_cent.mean()
spec_cent_mean

1147.2592587922977

In [16]:
df_spec_cent = pd.DataFrame(spec_cent)
df_spec_cent

0            1            2            3            4    \
0  1948.533535  2065.753235  2108.698768  1940.679747  1432.970128   

           5            6           7           8            9    ...  \
0  1220.546204  1424.068117  1878.26751  2019.98083  2392.985835  ...   

          630         631         632         633          634          635  \
0  564.619252  444.882319  473.510611  818.027129  1116.746677  1071.752333   

           636          637          638          639  
0  1213.875965  1509.856066  1550.391715  1497.810287  

[1 rows x 640 columns]

In [17]:
time_step = 1


In [18]:
Power_Spectrum = np.fft.fftfreq(y.size, time_step)
Power_Spectrum

array([ 0.00000000e+00,  3.05602924e-06,  6.11205848e-06, ...,
       -9.16808772e-06, -6.11205848e-06, -3.05602924e-06])

In [19]:
df_Power_Spectrum = pd.DataFrame(Power_Spectrum)
df_Power_Spectrum

0
0       0.000000
1       0.000003
2       0.000006
3       0.000009
4       0.000012
...          ...
327217 -0.000015
327218 -0.000012
327219 -0.000009
327220 -0.000006
327221 -0.000003

[327222 rows x 1 columns]

In [20]:
Power_Spectrum_mean = Power_Spectrum.mean()
Power_Spectrum_mean

-1.5280146200513542e-06

#สร้างตาราง


In [21]:
name = [{'mfcc_mean':'-6.3565636', 'lpc_test_mean':'0.0060151517', 'spec_cent_mean':'1147.2592587922977', 'zcr_mean':'0.05833511352539063', 'Power_Spectrum_mean':'-1.5280146200513542e-06'}]

In [22]:
data_ = [[-6.3565636], [0.0060151517], [1147.2592587922977], [0.05833511352539063], [-1.5280146200513542e-06]]
data_

[[-6.3565636],
 [0.0060151517],
 [1147.2592587922977],
 [0.05833511352539063],
 [-1.5280146200513542e-06]]

In [23]:
data_set = pd.DataFrame(name)
data_set

mfcc_mean lpc_test_mean      spec_cent_mean             zcr_mean  \
0  -6.3565636  0.0060151517  1147.2592587922977  0.05833511352539063   

       Power_Spectrum_mean  
0  -1.5280146200513542e-06

In [10]:
tonnezt = librosa.feature.tonnetz( y=y, sr=44100, chroma=None)
tonnezt

array([[-0.00025474,  0.004947  ,  0.00785755, ..., -0.05617889,
        -0.05030206, -0.05102602],
       [-0.00103631, -0.00644895, -0.00499784, ...,  0.02428073,
         0.00960029,  0.00714675],
       [ 0.01337524,  0.01654461,  0.02057866, ..., -0.03185244,
        -0.01956078, -0.01052299],
       [-0.02947187, -0.03157765, -0.03394368, ..., -0.14900953,
        -0.14455618, -0.13819329],
       [ 0.00979501,  0.01164257,  0.01392158, ...,  0.0349659 ,
         0.02739622,  0.02397067],
       [ 0.0227814 ,  0.02030941,  0.01552781, ...,  0.00547706,
         0.00670638,  0.00367871]])

In [11]:
df_Tonnezt = pd.DataFrame(tonnezt)
df_Tonnezt



0         1         2         3         4         5         6    \
0 -0.000255  0.004947  0.007858  0.009797  0.011642  0.009119  0.007442   
1 -0.001036 -0.006449 -0.004998 -0.003445 -0.002731  0.003002  0.006522   
2  0.013375  0.016545  0.020579  0.027742  0.025301  0.018045  0.006717   
3 -0.029472 -0.031578 -0.033944 -0.034525 -0.032415 -0.036749 -0.047527   
4  0.009795  0.011643  0.013922  0.015688  0.015692  0.012529  0.009183   
5  0.022781  0.020309  0.015528  0.010238  0.005567  0.002738  0.000854   

        7         8         9    ...       630       631       632       633  \
0  0.005956  0.007588  0.016739  ... -0.115475 -0.101142 -0.096908 -0.085380   
1  0.010936  0.013615  0.013729  ...  0.125268  0.101666  0.087980  0.071626   
2 -0.000173 -0.010266 -0.012813  ... -0.105477 -0.095112 -0.083506 -0.067741   
3 -0.062063 -0.074700 -0.079710  ... -0.169918 -0.165490 -0.166758 -0.169066   
4  0.006884  0.008109  0.013102  ...  0.058620  0.060097  0.058232  0.055498   
5  0.001364  0.002572  0.004599  ... -0.035307 -0.029272 -0.023980 -0.017088   

        634       635       636       637       638       639  
0 -0.074459 -0.064741 -0.058805 -0.056179 -0.050302 -0.051026  
1  0.057728  0.046178  0.034395  0.024281  0.009600  0.007147  
2 -0.057116 -0.051163 -0.040419 -0.031852 -0.019561 -0.010523  
3 -0.168893 -0.168790 -0.162441 -0.149010 -0.144556 -0.138193  
4  0.052059  0.047907  0.042326  0.034966  0.027396  0.023971  
5 -0.009473 -0.001027  0.004914  0.005477  0.006706  0.003679  

[6 rows x 640 columns]

In [12]:
tonneztScaled = np.mean(tonnezt.T, axis=0) #axis=0 คือทำงานในแนวคอลัมล์
tonneztScaled

array([ 0.01015276, -0.00456723,  0.01240696, -0.02048932,  0.00201617,
       -0.00802679])

In [13]:
df_tonneztScaled = pd.DataFrame(tonneztScaled)
df_tonneztScaled

0
0  0.010153
1 -0.004567
2  0.012407
3 -0.020489
4  0.002016
5 -0.008027